# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/bookings" do
  describe "GET /index" do
    before do
      create(:booking)
      get api_v1_bookings_url
    end

    it "renders a successful response" do
      expect(response).to have_http_status(:success)
    end
  end

  describe "GET /show" do
    let!(:booking) { create(:booking, vehicle_type: :small) }

    before { get api_v1_booking_url(booking) }

    it "renders a successful response" do
      expect(response).to have_http_status(:success)
      json = response.parsed_body
      expect(json["vehicle_type"]).to eq("small")
      expect(json["plate_number"]).to eq("ABC123")
    end
  end
end
