# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/parking_slots", type: :request do
  let!(:parking_lot) { create :parking_lot }

  describe "GET /index" do
    before do
      ParkingSlot.destroy_all
      create_pair(:parking_slot, parking_lot:)
      get api_v1_parking_slots_url
    end

    it "renders a successful response" do
      expect(response).to have_http_status(:success)
      parking_slots = response.parsed_body
      expect(parking_slots.size).to eq(2)
    end
  end
end
